name: DevSecOps Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  devsecops:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    # -------------------------
    # Install tools
    # -------------------------
    - name: Install Trivy
      run: |
        sudo apt-get install wget apt-transport-https gnupg lsb-release -y
        wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
        echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main | sudo tee -a /etc/apt/sources.list.d/trivy.list
        sudo apt-get update
        sudo apt-get install trivy -y

    - name: Install Hadolint
      run: |
        wget -O /usr/local/bin/hadolint https://github.com/hadolint/hadolint/releases/latest/download/hadolint-Linux-x86_64
        chmod +x /usr/local/bin/hadolint

    - name: Install Conftest (OPA)
      run: |
        curl -L -o conftest https://github.com/open-policy-agent/conftest/releases/latest/download/conftest-linux-amd64
        chmod +x conftest
        sudo mv conftest /usr/local/bin/

    - name: Install pip-audit
      run: |
        python3 -m pip install --upgrade pip
        pip install pip-audit

    # -------------------------
    # Lint Dockerfile
    # -------------------------
    - name: Lint Dockerfile
      run: hadolint ./Dockerfile || true  # Do not fail pipeline yet

    # -------------------------
    # Upgrade Python dependencies
    # -------------------------
    - name: Upgrade vulnerable packages
      run: |
        pip install --upgrade flask>=3.1.3 jinja2>=3.1.6 requests>=2.32.4 setuptools>=78.1.1 twisted>=24.7.0rc1 urllib3>=2.6.3 wheel>=0.46.2 cryptography>=46.0.5 certifi>=2024.7.4 configobj>=5.0.9 idna>=3.7

    # -------------------------
    # Pip Audit
    # -------------------------
    - name: Pip Audit
      run: pip-audit

    # -------------------------
    # Build Docker Image
    # -------------------------
    - name: Build Docker Image
      run: docker build -t devsecops-demo:latest .

    # -------------------------
    # Scan Container Image
    # -------------------------
    - name: Scan Container Image
      run: trivy image devsecops-demo:latest || true

    # -------------------------
    # Policy Check
    # -------------------------
    - name: Run OPA/Conftest Policy
      run: |
        mkdir -p policies
        echo "package main\n\ndeny[msg] {\n  input.User == \"root\"\n  msg = \"Do not run as root\"\n}" > policies/docker_policy.rego
        conftest test Dockerfile --policy ./policies || true

    # -------------------------
    # Generate Consolidated Report
    # -------------------------
    - name: Generate Markdown Report
      run: |
        mkdir -p reports
        echo "# DevSecOps Pipeline Report" > reports/latest_report.md
        echo "## Dockerfile Linting" >> reports/latest_report.md
        hadolint ./Dockerfile >> reports/latest_report.md || echo "Lint passed" >> reports/latest_report.md
        echo "## Trivy Filesystem Scan" >> reports/latest_report.md
        trivy fs --security-checks vuln,config . >> reports/latest_report.md || echo "No vulnerabilities found" >> reports/latest_report.md
        echo "## Pip Audit" >> reports/latest_report.md
        pip-audit >> reports/latest_report.md || echo "No vulnerabilities found" >> reports/latest_report.md
        echo "## Container Image Scan" >> reports/latest_report.md
        trivy image devsecops-demo:latest >> reports/latest_report.md || echo "No vulnerabilities found" >> reports/latest_report.md
        echo "## OPA Policy Check" >> reports/latest_report.md
        conftest test Dockerfile --policy ./policies >> reports/latest_report.md || echo "All policies passed" >> reports/latest_report.md

    # ------------------------
    #  Send out Markdown Report
    #  -----------------------
    - name: Send Report via Email
      run: |
        python3 scripts/send_email.py
      env:
        EMAIL_ADDRESS: ${{ secrets.EMAIL_ADDRESS }}
        EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        TO_EMAIL: $ {{ secrets.TO_EMAIL }}

    # -------------------------
    # DockerHub Push
    # -------------------------
    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Docker Image
      run: |
        docker tag devsecops-demo:latest ${{ secrets.DOCKER_USERNAME }}/devsecops-demo:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/devsecops-demo:latest

